services:
  - type: web
    name: jiuweihu-ai-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: DEEPSEEK_API_KEY
        value: sk-a71f8c3f43c748dc970ce1fa872b472b
